### ISSUE TITLE
[INFO] Wrong username and password combination

### ISSUE THREAD

**Issue by kevindaus** [afsalashyana/Library-Assistant#2]
If someone evere encounter wrong username and combination . Run https://github.com/afsalashyana/Library-Assistant/blob/master/src/library/assistant/settings/SettingsLoader.java under your project and change the username and password

**Comment by afsalashyana** [comment]
Thanks for sharing.
I accidentally pushed the config.txt file that changed the username and password to 'gc' and 'root' respectively. The file has been recommitted with default 'admin' and 'admin'
