### ISSUE TITLE
The project started with the screenshot is not the same

### ISSUE THREAD

**Issue by i-CNNN** [afsalashyana/Library-Assistant#3]
Hello,

Where do i need to change my screen shots? This decorator is the system default, not custom.

![image](https://user-images.githubusercontent.com/24954758/34820018-5a6493e6-f6fa-11e7-8563-e0a3d8ce814e.png)

**Comment by afsalashyana** [comment]
The program uses decorated window only.
In the screenshot, Windows 10 title bar colour is changed to match with the theme.
However, If you want, you can set the stage to UNDECORATED and implement your own title bar.
