### ISSUE TITLE
How do i update username and password?

### ISSUE THREAD

**Issue by sunmughan** [afsalashyana/Library-Assistant#5]
unable to change password and username. Kjndlh help me out as admin is a weak password.

**Comment by afsalashyana** [comment]
You can easily change username and password from Settings.
Settings is available via 'File -> Settings' or through Side Panel.

![image](https://user-images.githubusercontent.com/7298503/48916402-2e175e80-eea8-11e8-9203-a64141ff0d2a.png)

**Comment by sunmughan** [comment]
Thankyou sir, but i was asking regarding login credentials. While login its
using (admin, admin) so i was asking if it would be possible to modify it
likewise 😊

**Comment by afsalashyana** [comment]
If you change the username and password here, it will change for login also.
