### ISSUE TITLE
I can't open fxml file

### ISSUE THREAD

**Issue by alwaysForTop** [afsalashyana/Library-Assistant#7]
details: ClassNotFoundException: com.jfoenix.controls.JFXButton
but i can run the project...
I sure,I have imported jfoenix-8.0.4.jar

**Comment by alwaysForTop** [comment]
I can't find fontawesomeiconview in scene builder

**Comment by afsalashyana** [comment]
Hi,
Have you found solution for your issue ?

**Comment by afsalashyana** [comment]
Closing issue now. Feel free to reopen if required.
