### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Tall-Lobster** [afsalashyana/Library-Assistant#9]
I am trying to build the project from the source code but I am facing the issue where I cannot build it. It would be great if you could provide instructions on how to build the project in the readme or another file

**Comment by afsalashyana** [comment]
You can build this program directly from NetBeans.
Open this project in NetBeans. Right click on project -> Clean and build
You will get the JAR file along with its dependencies in 'dist' folder in your project root directory.

**Comment by Tall-Lobster** [comment]
Wait so you are telling me that I need NetBeans to run this edit the code?

**Comment by afsalashyana** [comment]
Yes.
For building, you need NetBeans IDE
